{
 "title": "ELK Kubernetes",
 "description": "All the Elk metrics you desire",
 "tags": [ "myapp" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "kafka_cluster",
    "query": "kafka_server_KafkaServer_Value{name=\"BrokerState\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Log Messages Unfiltered (ingress)",
   "type": "singlestat",
   "description": "Log messages that have entered Kafka yet to be filtered.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(kafka_server_BrokerTopicMetrics_Count{name=\"MessagesInPerSec\",service=\"$kafka_cluster\",topic=\"unfiltered-kubernetes\"}[1m]))"
    }
   ]
  },
  {
   "title": "Log Messages Filtered (elk-ready)",
   "type": "singlestat",
   "description": "Log messages filtered, ready to be indexed into ES",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(kafka_server_BrokerTopicMetrics_Count{name=\"MessagesInPerSec\",service=\"$kafka_cluster\",topic=\"elk-ready\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total Messages Produced Per Second",
   "type": "singlestat",
   "description": "Counter of all messages produced per second to ALL Kafka topics.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(kafka_server_BrokerTopicMetrics_Count{name=\"MessagesInPerSec\",service=\"$kafka_cluster\",topic!=\"\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total Messages Produced Per Minute",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(kafka_server_BrokerTopicMetrics_Count{name=\"MessagesInPerSec\",service=\"$kafka_cluster\",topic!=\"\"}[1m]))*60"
    }
   ]
  },
  {
   "title": "Total Messages Produced Per Hour",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(kafka_server_BrokerTopicMetrics_Count{name=\"MessagesInPerSec\",service=\"$kafka_cluster\",topic!=\"\"}[1m]))*60*60"
    }
   ]
  },
  {
   "title": "Total Messages Produced Per Day",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(kafka_server_BrokerTopicMetrics_Count{name=\"MessagesInPerSec\",service=\"$kafka_cluster\",topic!=\"\"}[1m]))*60*60*24*7"
    }
   ]
  },
  {
   "title": "Messages In Per Topic",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum by (topic)(rate(kafka_server_BrokerTopicMetrics_Count{name=\"MessagesInPerSec\",service=\"$kafka_cluster\",topic!=\"\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum by (topic)(kafka_server_BrokerTopicMetrics_MeanRate{name=\"BytesInPerSec\",service=\"$kafka_cluster\",topic!=\"\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum by (topic)(kafka_server_BrokerTopicMetrics_MeanRate{name=\"BytesOutPerSec\",service=\"$kafka_cluster\",topic!=\"\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{service=\"$kafka_cluster\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Kafka JVM Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{service=\"$kafka_cluster\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Kafka Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "percentunit", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{service=\"$kafka_cluster\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Logstash CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{pod_name=~\"logstash.*\", container_name!=\"POD\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "container_spec_cpu_quota{container=\"logstash\",pod=~\"logstash.*\"}/100000",
     "legendFormat": "CPU Limit - {{pod_name}}"
    }
   ]
  },
  {
   "title": "Logstash Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "short", "label": "Memory Usage" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container=\"\",pod=~\"logstash.*\"}/1024/1024",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "container_spec_memory_limit_bytes{container=\"\",pod=~\"logstash.*\"}/1024/1024",
     "legendFormat": "Memory Limit - {{pod}}"
    }
   ]
  },
  {
   "title": "Logstash JVM Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "short", "label": "Memory Usage" }
   ],
   "targets": [
    {
     "expr": "logstash_node_mem_heap_used_bytes{pod=~\"logstash.*\"}/1024/1024",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "logstash_node_mem_heap_max_bytes{pod=~\"logstash.*\"}/1024/1024",
     "legendFormat": "Heap Limit - {{pod}}"
    }
   ]
  },
  {
   "title": "Logstash Pipeline In",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "rate(logstash_node_pipeline_events_in_total[1m])",
     "legendFormat": "{{pipeline}}"
    }
   ]
  },
  {
   "title": "Logstash Pipeline Out",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "rate(logstash_node_pipeline_events_out_total[1m])",
     "legendFormat": "{{pipeline}}"
    }
   ]
  },
  {
   "title": "Logstash Pipeline Filtered",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "rate(logstash_node_pipeline_events_filtered_total[1m])",
     "legendFormat": "{{pipeline}}"
    }
   ]
  },
  {
   "title": "Logstash Thread Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "logstash_node_jvm_threads_count",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}