{
 "title": "Jenkins - Kubernetes",
 "description": "Jobs queue speeds and rates, Executors availability, Nodes status, Jenkins and JVM resource usage.",
 "tags": [ "myapp" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job_name", "query": "default_jenkins_up" }
  ]
 },
 "panels": [
  {
   "title": "POD CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{container=\"\",pod=~\"$job_name.*\"}",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "container_spec_cpu_quota{pod=~\"$job_name.*\"}/100",
     "legendFormat": "CPU Limit"
    }
   ]
  },
  {
   "title": "POD MEM Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container=\"\",pod=~\"$job_name.*\"}/1024/1024",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{pod=~\"$job_name.*\"})/1024/1024",
     "legendFormat": "Memory Limit"
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "vm_memory_heap_used{pod=~\"$job_name.*\"}/1024/1024",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "jvm_memory_bytes_max{area=\"heap\",pod=~\"$job_name.*\"}/1024/1024",
     "legendFormat": "Memory Limit"
    }
   ]
  },
  {
   "title": "Job queue duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "jenkins_job_queuing_duration{job=\"$job_name\"}",
     "legendFormat": "Queue Duration Quantile ({{quantile}})"
    }
   ]
  },
  {
   "title": "Job waiting duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "jenkins_job_waiting_duration{job=\"$job_name\"}",
     "legendFormat": "Waiting Duration Quantile ({{quantile}})"
    }
   ]
  },
  {
   "title": "Job total duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "jenkins_job_total_duration{job=\"$job_name\"}",
     "legendFormat": "Queue Duration Quantile ({{quantile}})"
    }
   ]
  },
  {
   "title": "Plugins active",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jenkins_plugins_active{job=\"$job_name\"}"
    }
   ]
  },
  {
   "title": "Jenkins health",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jenkins_health_check_score{job=\"$job_name\"}"
    }
   ]
  },
  {
   "title": "Nodes online",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jenkins_node_online_value{job=\"$job_name\"}"
    }
   ]
  },
  {
   "title": "Nodes offline",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jenkins_node_offline_value{job=\"$job_name\"}"
    }
   ]
  },
  {
   "title": "Jenkins plugins failed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jenkins_plugins_failed{job=\"$job_name\"}"
    }
   ]
  },
  {
   "title": "JVM uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 16 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "vm_uptime_milliseconds{job=\"$job_name\"}"
    }
   ]
  },
  {
   "title": "Queue size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jenkins_queue_size_value{job=\"$job_name\"}"
    }
   ]
  },
  {
   "title": "Executors health",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "Executors" }
   ],
   "targets": [
    {
     "expr": "jenkins_executor_count_value{job=\"$job_name\"}",
     "legendFormat": "Total Executors"
    },
    {
     "expr": "jenkins_executor_free_value{job=\"$job_name\"}",
     "legendFormat": "Free Executors"
    }
   ]
  },
  {
   "title": "Most Successful Builds",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 30 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "topk(5, max(default_jenkins_builds_success_build_count{job=\"$job_name\"}) by (jenkins_job))",
     "legendFormat": "{{jenkins_job}}"
    }
   ]
  },
  {
   "title": "Most Failed Builds",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 30 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "topk(5, max(default_jenkins_builds_failed_build_count{job=\"$job_name\"}) by (jenkins_job))",
     "legendFormat": "{{jenkins_job}}"
    }
   ]
  },
  {
   "title": "Node CPU Usage %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(kube_pod_container_resource_requests_cpu_cores)  by (node) / node:node_num_cpu:sum)*100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node Memory Usage %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(\n(node_memory_MemTotal_bytes{job=\"node-exporter\"}\n    - node_memory_MemFree_bytes{job=\"node-exporter\"}\n    - node_memory_Buffers_bytes{job=\"node-exporter\"}\n    - node_memory_Cached_bytes{job=\"node-exporter\"} )\n    / node_memory_MemTotal_bytes{job=\"node-exporter\"}\n) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}