{{- if or .Values.monitor_istio .Values.monitor_service_accounts }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.cluster_role_name }}
rules:
{{- if .Values.monitor_service_accounts}}
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"] # Allow Defenders to list RBAC resources
  verbs: ["list"]
{{- end}}
{{- if .Values.monitor_istio}}
- apiGroups: ["rbac.istio.io"]
  resources: ["rbacconfigs", "servicerolebindings", "serviceroles"] # Allow Defenders to list Istio RBAC resources
  verbs: ["list"]
- apiGroups: ["authentication.istio.io"]
  resources: ["meshpolicies"] # Allow Defenders to list Istio mesh policies
  verbs: ["list"]
- apiGroups: ["networking.istio.io"]
  resources: ["virtualservices", "destinationrules", "gateways", "serviceentries"] # Allow Defenders to list Istio networking resources
  verbs: ["list"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "endpoints"] # Allow Defenders to list pods and service endpoints
  verbs: ["list"]
{{- end}}
{{- end}}