{
 "title": "Brokers",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": "label_values(instance) " }
  ]
 },
 "panels": [
  {
   "title": "Fetch request Purgatorysize",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_delayedoperationpurgatory_purgatorysize_delayedoperation_fetch{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "kafka_cluster_down",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg (up{job=\"kafka\"}) BY (job)"
    }
   ]
  },
  {
   "title": "file descriptors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_max_fds{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "active_controller_status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "absent(kafka_controller_kafkacontroller_activecontrollercount{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "kafka_status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(up{instance=\"$instance\"}[5m])"
    }
   ]
  },
  {
   "title": "Under replicated partitions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(kafka_server_replicamanager_underreplicatedpartitions[1m]) > 0 "
    }
   ]
  },
  {
   "title": "Unclean/leader elctions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " kafka_controller_controllerstats_uncleanleaderelectionspersec{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Huge traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_messagesin_total{topic!=\"\",instance=\"$instance\"}[10m]) > 10"
    }
   ]
  }
 ]
}