{
 "title": "Mesos DEV Cassandra",
 "description": "Display cassandra node detail in OS, Cassandra and JVM blocks",
 "tags": [
  "mesos",
  "cassandra"
 ],
 "time": { "from": "now/w", "to": "now/w" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(org_apache_cassandra_metrics_clientrequest_latency_casread_max, service_name)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "# Cassandra Clusters\nDev: e85da24d-3f90-445e-872b-3474fa93845a-0000  \nIDev: db55dc71-4dcd-439d-b194-01652cf7f7e1-0000  "
  },
  { "title": "Client Read/Write Failure Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Client Read Failure Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_apache_cassandra_metrics_clientrequest_failures_casread_m1_rate{service_name=\"$cluster\"}",
     "legendFormat": "{{task_name}}-{{service_name}}-m1_rate"
    },
    {
     "expr": "org_apache_cassandra_metrics_clientrequest_failures_casread_m5_rate{service_name=\"$cluster\"}",
     "legendFormat": "{{task_name}}-{{service_name}}-m5_rate"
    },
    {
     "expr": "org_apache_cassandra_metrics_clientrequest_failures_casread_m15_rate{service_name=\"$cluster\"}",
     "legendFormat": "{{task_name}}-{{service_name}}-m15_rate"
    }
   ]
  },
  {
   "title": "Client Write Failure Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_apache_cassandra_metrics_clientrequest_failures_caswrite_m1_rate{service_name=\"$cluster\"}",
     "legendFormat": "{{task_name}}-{{service_name}}-m1_rate"
    },
    {
     "expr": "org_apache_cassandra_metrics_clientrequest_failures_caswrite_m5_rate{service_name=\"$cluster\"}",
     "legendFormat": "{{task_name}}-{{service_name}}-m5_rate"
    },
    {
     "expr": "org_apache_cassandra_metrics_clientrequest_failures_caswrite_m15_rate{service_name=\"$cluster\"}",
     "legendFormat": "{{task_name}}-{{service_name}}-m15_rate"
    }
   ]
  },
  { "title": "Compaction & SSTables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Pending Compactions",
   "type": "graph",
   "description": "Number of compactions pending. If this is trending increasingly higher, it's a good indication there is a performance issue and should be investigated.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_apache_cassandra_metrics_compaction_pendingtasks{service_name=\"$cluster\"}",
     "legendFormat": "{{task_name}}-{{service_name}}-all"
    },
    {
     "expr": "org_apache_cassandra_metrics_keyspace_pendingcompactions_myapp{service_name=\"$cluster\"}",
     "legendFormat": "{{task_name}}-{{service_name}}-myapp"
    }
   ]
  },
  {
   "title": "SSTables - All",
   "type": "graph",
   "description": "Number of sstables. If this is trending increasingly higher, it's a good indication compaction isn't keeping up with the number of sstables being created, or some other performance related issue and should be investigated.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_apache_cassandra_metrics_table_livesstablecount_all{service_name=\"$cluster\"}",
     "legendFormat": "{{task_name}}-{{service_name}}-all"
    }
   ]
  },
  {
   "title": "SSTables",
   "type": "graph",
   "description": "Number of sstables. If this is trending increasingly higher, it's a good indication compaction isn't keeping up with the number of sstables being created, or some other performance related issue and should be investigated.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"org_apache_cassandra_metrics_table_livesstablecount_myapp.*\",service_name=\"$cluster\"}",
     "legendFormat": "{{task_name}}-{{__name__}}"
    }
   ]
  },
  { "title": "Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Keyspace Read Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "dtdurationms", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "org_apache_cassandra_metrics_keyspace_readlatency_myapp_max{service_name=\"$cluster\"}",
     "legendFormat": "{{task_name}}-{{service_name}}-MAX"
    },
    {
     "expr": "org_apache_cassandra_metrics_keyspace_readlatency_myapp_min{service_name=\"$cluster\"}",
     "legendFormat": "{{task_name}}-{{service_name}}-MIN"
    },
    {
     "expr": "org_apache_cassandra_metrics_keyspace_readlatency_myapp_p50{service_name=\"$cluster\"}",
     "legendFormat": "{{task_name}}-{{service_name}}-AVG"
    }
   ]
  },
  {
   "title": "Keyspace Write Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "dtdurationms", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "org_apache_cassandra_metrics_keyspace_writelatency_myapp_max{service_name=\"$cluster\"}",
     "legendFormat": "{{task_name}}-{{service_name}}-MAX"
    },
    {
     "expr": "org_apache_cassandra_metrics_keyspace_writelatency_myapp_min{service_name=\"$cluster\"}",
     "legendFormat": "{{task_name}}-{{service_name}}-MIN"
    },
    {
     "expr": "org_apache_cassandra_metrics_keyspace_writelatency_myapp_p50{service_name=\"$cluster\"}",
     "legendFormat": "{{task_name}}-{{service_name}}-AVG"
    }
   ]
  },
  {
   "title": "Keyspace Data Size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "bytes", "label": "Size" }
   ],
   "targets": [
    {
     "expr": "org_apache_cassandra_metrics_keyspace_livediskspaceused_myapp{service_name=\"$cluster\"}",
     "legendFormat": "{{task_name}}-{{service_name}}"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Connected Clients",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_apache_cassandra_metrics_client_connectednativeclients{service_name=\"$cluster\"}",
     "legendFormat": "{{task_name}}-{{service_name}}"
    }
   ]
  },
  {
   "title": "Reads/min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "Reads" }
   ],
   "targets": [
    {
     "expr": "increase(org_apache_cassandra_metrics_clientrequest_latency_read_samples{service_name=\"$cluster\"}[1m])",
     "legendFormat": "{{task_name}}-{{service_name}}-read"
    }
   ]
  },
  {
   "title": "Writes/min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "Writes" }
   ],
   "targets": [
    {
     "expr": "increase(org_apache_cassandra_metrics_clientrequest_latency_write_samples{service_name=\"$cluster\"}[1m])",
     "legendFormat": "{{task_name}}-{{service_name}}-write"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Storage Load",
   "type": "graph",
   "description": "Size, in bytes, of the on disk data size this node manages.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "org_apache_cassandra_metrics_storage_load{service_name=\"$cluster\"}",
     "legendFormat": "{{task_name}}-{{cluster}}"
    }
   ]
  },
  {
   "title": "Total Hints",
   "type": "graph",
   "description": "Number of hint messages written to this node since [re]start. Includes one entry for each host to be hinted per hint.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "Hints" }
   ],
   "targets": [
    {
     "expr": "org_apache_cassandra_metrics_storage_totalhints{service_name=\"$cluster\"}",
     "legendFormat": "{{task_name}}-{{cluster}}"
    }
   ]
  },
  {
   "title": "Total Hints In Progress",
   "type": "graph",
   "description": "Number of hint messages written to this node since [re]start. Includes one entry for each host to be hinted per hint.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "Hints In Progress" }
   ],
   "targets": [
    {
     "expr": "org_apache_cassandra_metrics_storage_totalhintsinprogress{service_name=\"$cluster\"}",
     "legendFormat": "{{task_name}}-{{cluster}}"
    }
   ]
  },
  {
   "title": "Cassandra Exceptions",
   "type": "singlestat",
   "description": "Number of internal exceptions caught. Under normal exceptions this should be zero.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 38 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "org_apache_cassandra_metrics_clientrequest_latency_casread_max{service_name=\"$cluster\"}"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Cassandra JVM Heap Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "bytes", "label": "Heap Used" }
   ],
   "targets": [
    {
     "target": "stats.mesosdev-bm-*.gauges.jvm.*.memory.heap.used"
    }
   ]
  },
  {
   "title": "Mesos Host Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Client Requests Read Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "dtdurationms", "label": "Latency" }
     ],
     "targets": [
      {
       "expr": "org_apache_cassandra_metrics_clientrequest_latency_casread_max{service_name=\"$cluster\"}",
       "legendFormat": "{{task_name}}-{{service_name}}-MAX"
      },
      {
       "expr": "org_apache_cassandra_metrics_clientrequest_latency_casread_min{service_name=\"$cluster\"}",
       "legendFormat": "{{task_name}}-{{service_name}}-MIN"
      },
      {
       "expr": "org_apache_cassandra_metrics_clientrequest_latency_casread_mean_rate{service_name=\"$cluster\"}",
       "legendFormat": "{{task_name}}-{{service_name}}-MEAN"
      }
     ]
    },
    {
     "title": "Client Requests Write Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 36 },
     "yaxes": [
      { "format": "dtdurationms", "label": "Latency" }
     ],
     "targets": [
      {
       "expr": "org_apache_cassandra_metrics_clientrequest_latency_caswrite_max{service_name=\"$cluster\"}",
       "legendFormat": "{{task_name}}-{{service_name}}-MAX"
      },
      {
       "expr": "org_apache_cassandra_metrics_clientrequest_latency_caswrite_min{service_name=\"$cluster\"}",
       "legendFormat": "{{task_name}}-{{service_name}}-MIN"
      },
      {
       "expr": "org_apache_cassandra_metrics_clientrequest_latency_caswrite_mean_rate{service_name=\"$cluster\"}",
       "legendFormat": "{{task_name}}-{{service_name}}-MEAN"
      }
     ]
    },
    {
     "title": "Total Timeouts",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "short", "label": "Timeouts" }
     ],
     "targets": [
      {
       "expr": "org_apache_cassandra_metrics_connection_totaltimeouts_mean_rate{service_name=\"$cluster\"}",
       "legendFormat": "{{task_name}}-{{service_name}}"
      }
     ]
    },
    {
     "title": "Compression Ratio",
     "type": "graph",
     "description": "Current compression ratio for all SSTables.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 36 },
     "yaxes": [
      { "format": "short", "label": "% Compression Ratio" }
     ],
     "targets": [
      {
       "expr": "org_apache_cassandra_metrics_table_compressionratio_all{service_name=\"$cluster\"}",
       "legendFormat": "{{task_name}}-{{service_name}}"
      }
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Disk Read OPs",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short", "label": "Read Operations" }
   ],
   "targets": [
    {
     "target": "collectd.mesosdev-bm-s0*_contino.io.disk-sd[d-k].disk_ops.read"
    }
   ]
  },
  {
   "title": "Disk Write OPs",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "short", "label": "Write Operations" }
   ],
   "targets": [
    {
     "target": "collectd.mesosdev-bm-s0*_contino.io.disk-sd[d-k].disk_ops.write"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short", "label": "Load" }
   ],
   "targets": [
    {
     "target": "collectd.mesosdev-bm-s*.load.load.shortterm"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "bytes", "label": "Memory Used" }
   ],
   "targets": [
    {
     "target": "collectd.mesosdev-bm-*.memory.memory-used"
    }
   ]
  },
  { "title": "Cassandra Load Test Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Cassandra-stress Average Read Latency",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 80 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_keyspace_readlatency_keyspace1_mean{service_name=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Cassandra-stress Average Write Latency",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 80 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(org_apache_cassandra_metrics_keyspace_writelatency_keyspace1_mean{service_name=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Operations/min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 80 },
   "yaxes": [
    { "format": "short", "label": "Operations" }
   ],
   "targets": [
    {
     "expr": "sum(increase(org_apache_cassandra_metrics_clientrequest_latency_read_samples{service_name=\"$cluster\"}[1m]))",
     "legendFormat": "Writes/min"
    },
    {
     "expr": "sum(increase(org_apache_cassandra_metrics_clientrequest_latency_write_samples{service_name=\"$cluster\"}[1m]))",
     "legendFormat": "Reads/min"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Cassandra-Stress Latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "dtdurationms", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "org_apache_cassandra_metrics_keyspace_writelatency_keyspace1_mean{service_name=\"$cluster\"}",
     "legendFormat": "{{task_name}}-{{service_name}}-WRITE-MEAN"
    },
    {
     "expr": "org_apache_cassandra_metrics_keyspace_readlatency_keyspace1_mean{service_name=\"$cluster\"}",
     "legendFormat": "{{task_name}}-{{service_name}}-READ-MEAN"
    },
    {
     "expr": "org_apache_cassandra_metrics_keyspace_writelatency_keyspace1_p999{service_name=\"$cluster\"}",
     "legendFormat": "{{task_name}}-{{service_name}}-WRITE-P999"
    },
    {
     "expr": "org_apache_cassandra_metrics_keyspace_readlatency_keyspace1_p999{service_name=\"$cluster\"}",
     "legendFormat": "{{task_name}}-{{service_name}}-READ-P999"
    }
   ]
  }
 ]
}