{
 "title": "batch",
 "tags": [ "myapp" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "label": "environment", "query": "dev,idev,qa,uat,stage,prod" }
  ]
 },
 "panels": [
  {
   "title": "medfulfillment_batchcommand_total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(myapp_medfulfillment_batchcommand_total{env=\"$env\"}[5m])) by (facilityNumber)"
    }
   ]
  },
  {
   "title": "labfulfillment_labtubebatch_total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(myapp_labfulfillment_labtubebatch_total{env=\"$env\"}[5m])) by (facilityNumber)"
    }
   ]
  },
  {
   "title": "medfulfillment_orderstaging_total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(myapp_medfulfillment_orderstaging_total{env=\"$env\"}[5m])) by (facilityNumber)"
    }
   ]
  },
  {
   "title": "labfulfillment_odmeligibility_total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(myapp_labfulfillment_odmeligibility_total{env=\"$env\"}[5m])) by (facilityNumber)"
    }
   ]
  },
  {
   "title": "medfulfillment_order_total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(myapp_medfulfillment_order_total{env=\"$env\"}[5m])) by (facilityNumber)"
    }
   ]
  },
  {
   "title": "myapp_medfulfillment_batchcommand_total exception",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(myapp_medfulfillment_batchcommand_total{env=\"$env\",exception!=\"\"})"
    }
   ]
  }
 ]
}