{
 "title": "Dashboard POC",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "label": "env", "query": "qa,dev,int,uat,stage" }
  ]
 },
 "panels": [
  { "title": "Nginix Proxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Proxy 5xx Error count",
   "type": "singlestat",
   "description": "The number of nginx proxy 500 errors.",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "ucp_access_label:\"$env\" AND access_log_req_host:\"myapp-dashboard-$env.contino.io\" AND service_name:\"$env-infra_proxy\" AND response:[500 TO 599]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Volume of requests vs failed requests",
   "type": "graph",
   "description": "Displays the total volume of requests vs the unsuccessful requests.",
   "gridPos": { "h": 7, "w": 10, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "unsuccessful requests",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "ucp_access_label:\"$env\" AND access_log_req_host:\"myapp-$env.contino.io\" AND service_name:\"$env-infra_proxy\" AND response:[500 TO 599]",
     "timeField": "@timestamp"
    },
    {
     "alias": "volume of requests",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "ucp_access_label:\"$env\" AND access_log_req_host:\"myapp-$env.contino.io\" AND service_name:\"$env-infra_proxy\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top 5 Slowest Path",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "request_element2.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "3", "size": "5" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "datacenter" ], "type": "tag" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "logins.count",
     "metrics": [
      {
       "field": "access_log_urt",
       "id": "3",
       "inlineScript": "_value*1000",
       "meta": {},
       "settings": { "script": { "inline": "_value*1000" } },
       "type": "avg"
      }
     ],
     "query": "(access_log_req_host:\"myapp-$env.contino.io\" OR access_log_request_host:\"myapp-api-$env\") AND NOT request_element2.keyword:infra*metrics",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "apps.backend.select metric",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "myapp", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Microservice Error Rate per Second",
   "type": "graph",
   "description": "This shows the current/average rate of 500 errors per microservices. This panels datasource comes metrics being scraped off microservices. Calculated as operations per second (ops).",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"5..\",instance=\"myapp-api-$env.contino.io:443\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"5..\",instance=\"myapp-zuul-$env.contino.io:443\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Microservice Response Rate",
   "type": "graph",
   "description": "This shows the current/average response rate per second of microservices. Calculated as operations per second (ops).",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{instance=\"myapp-api-$env.contino.io:443\", status!=\"5..\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{instance=\"myapp-zuul-$env.contino.io:443\", status!=\"5..\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Kafka Messages In per Second by Cluster",
   "type": "graph",
   "description": "Shows current/average rate of kafka messages in per second",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_messagesinpersec_all_1minuterate{service_name=\"/$env/confluent-kafka\"}) by(service_name)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Kafka Avg Request Wait Time in Request Queue (ms)",
   "type": "graph",
   "description": "Shows average/vurrent request wait time in queue / milisecond",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_network_requestmetrics_requestqueuetimems_mean{service_name=\"/$env/confluent-kafka\"})",
     "legendFormat": "$env"
    }
   ]
  },
  {
   "title": "Kafka Average Request Time (ms) by Cluster",
   "type": "graph",
   "description": "Shows current/average kafka request time in miliseconds.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_network_requestmetrics_localtimems_mean{service_name=\"/$env/confluent-kafka\"}) by (service_name)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Kafka Network Request Rate / sec by host",
   "type": "graph",
   "description": "Shows the network request rate per second by Kafka hosts.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_fetcherstats_requestspersec_15minuterate{service_name=\"/$env/confluent-kafka\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "Cassandra", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Connected Clients by Cluster",
   "type": "singlestat",
   "description": "Shows current clients connected by cassandra cluster ",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_client_connectednativeclients{service_name=\"/$env/cassandra\"}) by (service_name)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Cassandra Read Latency (ms)",
   "type": "graph",
   "description": "Shows read latency for cassandra hosts.",
   "gridPos": { "h": 7, "w": 10, "x": 3, "y": 28 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "org_apache_cassandra_metrics_clientrequest_latency_read_all_min{service_name=\"/$env/cassandra\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Cassandra Write Latency (ms)",
   "type": "graph",
   "description": "Shows write latency for Cassandra Hosts",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 28 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "org_apache_cassandra_metrics_clientrequest_latency_write_all_min{service_name=\"/$env/cassandra\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Jenkins",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 Failing Jenkins Jobs",
     "type": "stat",
     "description": "Shows the top 5 failing Jenkins Jobs. The number displayed to the right specifies the quantity job failures over the selected time range. ",
     "gridPos": { "h": 6, "w": 23, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "topk(5, max(default_jenkins_builds_failed_build_count{instance=\"canary-jenkins.contino.io:443\"}) by (jenkins_job, instance))",
       "legendFormat": "{{jenkins_job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Batch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Med Batch Exceptions",
     "type": "stat",
     "description": "Shows exception rate for the myapp batch job",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "count(myapp_batchcommand_total{exception!=\"\",env=~\"$env\"}) by (env)",
       "legendFormat": "{{env}}"
      }
     ]
    },
    {
     "title": "Batch2 Exception Count",
     "type": "stat",
     "description": "Shows the exception rate for the myapp_batch2 batch job.",
     "gridPos": { "h": 8, "w": 12, "x": 11, "y": 37 },
     "targets": [
      {
       "expr": "count(myapp_batch2_total{exception!=\"\", env=\"$env\"}) by (exception)",
       "legendFormat": "{{exception}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DDC Exited Containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "DEV dockerworker01",
     "type": "gauge",
     "description": "Shows Active vs Exited docker containers per docker worker",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 20 },
     "targets": [
      {
       "target": "alias(collectd.devdockerworker01_contino_io.docker-containers.*, 'active containers')"
      },
      {
       "target": "alias(collectd.devdockerworker01_contino_io.docker-dead-containers.*, 'exited containers')"
      }
     ]
    },
    {
     "title": "DEV dockerworker02",
     "type": "gauge",
     "description": "Shows Active vs Exited docker containers per docker worker",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 20 },
     "targets": [
      {
       "target": "alias(collectd.devdockerworker02_contino_io.docker-containers.*, 'active containers')"
      },
      {
       "target": "alias(collectd.devdockerworker02_contino_io.docker-dead-containers.*, 'exited containers')"
      }
     ]
    },
    {
     "title": "DEV dockerworker03",
     "type": "gauge",
     "description": "Shows Active vs Exited docker containers per docker worker",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 20 },
     "targets": [
      {
       "target": "alias(collectd.devdockerworker03_contino_io.docker-containers.*, 'active containers')"
      },
      {
       "target": "alias(collectd.devdockerworker03_contino_io.docker-dead-containers.*, 'exited containers')"
      }
     ]
    },
    {
     "title": "QA dockerworker01",
     "type": "gauge",
     "description": "Shows Active vs Exited docker containers per docker worker",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 20 },
     "targets": [
      {
       "target": "alias(collectd.devdockerqaworker01_contino_io.docker-containers.*, 'active containers')"
      },
      {
       "target": "alias(collectd.devdockerqaworker01_contino_io.docker-dead-containers.*, 'exited containers')"
      }
     ]
    },
    {
     "title": "QA dockerworker02",
     "type": "gauge",
     "description": "Shows Active vs Exited docker containers per docker worker",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 20 },
     "targets": [
      {
       "target": "alias(collectd.devdockerqaworker02_contino_io.docker-containers.*, 'active containers')"
      },
      {
       "target": "alias(collectd.devdockerqaworker02_contino_io.docker-dead-containers.*, 'exited containers')"
      }
     ]
    },
    {
     "title": "QA dockerworker03",
     "type": "gauge",
     "description": "Shows Active vs Exited docker containers per docker worker",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 20 },
     "targets": [
      {
       "target": "alias(collectd.devdockerworker03_contino_io.docker-containers.*, 'active containers')"
      },
      {
       "target": "alias(collectd.devdockerworker03_contino_io.docker-dead-containers.*, 'exited containers')"
      }
     ]
    }
   ]
  }
 ]
}