{
 "title": "local",
 "time": { "from": "2019-09-14T15:48:22.622Z", "to": "2020-01-20T15:48:22.622Z" },
 "templating": {
  "list": [
   { "name": "env", "label": "environment", "query": "dev,idev,qa,uat,staging,prod" }
  ]
 },
 "panels": [
  {
   "title": "API request rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{env=\"$env\",uri=~\"/api/.*\"}[5m])"
    }
   ]
  },
  {
   "title": "Log Error count",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "increase(logback_events_total{env=\"$env\",level=\"error\"}[5m])"
    }
   ]
  },
  {
   "title": "Orders total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(beer_orders_total{env=\"$env\"}[5m])"
    }
   ]
  },
  {
   "title": "orders in queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(beer_ordersInQueue{env=\"$env\"}[5m])"
    }
   ]
  }
 ]
}