{
 "title": "PRODUCER",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "topic", "label": "topic", "query": "label_values(topic) " }
  ]
 },
 "panels": [
  {
   "title": "TotalProduceRequestsPerSec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_totalproducerequests_total{topic=~\"$topic\"}"
    }
   ]
  },
  {
   "title": "MessagesInPerSec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_messagesin_total{topic=\"$topic\",}[2m])*60"
    }
   ]
  },
  {
   "title": "Partition_LastStableOffsetLag",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_cluster_partition_laststableoffsetlag{partition=\"0\",topic=~\"$topic\",}"
    }
   ]
  },
  {
   "title": "BytesIn_OutPerSec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_bytesin_total{topic=~\"$topic\",}"
    },
    {
     "expr": "kafka_server_brokertopicmetrics_bytesout_total{topic=~\"$topic\",}"
    }
   ]
  },
  {
   "title": "TotalFetchRequestsPerSec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_totalfetchrequests_total{topic=~\"$topic\",}"
    }
   ]
  },
  {
   "title": "NumLogSegments",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_log_numlogsegments{partition=\"0\",topic=~\"$topic\",}"
    }
   ]
  },
  {
   "title": "FailedProduceRequestsPerSec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_failedproducerequests_total{topic=~\"$topic\",}"
    }
   ]
  },
  {
   "title": "LogStart_EndOffset",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_log_logstartoffset{partition=\"0\",topic=~\"$topic\",}"
    },
    {
     "expr": "kafka_log_logendoffset{partition=\"0\",topic=~\"$topic\",}"
    }
   ]
  },
  {
   "title": "LogSize",
   "type": "graph",
   "description": "t.dxf.provwithoff.in",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_log_size{partition=\"0\",topic=~\"$topic\",}"
    }
   ]
  },
  {
   "title": "FailedFetchRequestsPerSec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_failedfetchrequests_total{topic=~\"$topic\",}"
    }
   ]
  }
 ]
}