{
 "title": "Zookeeper",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Zookeeper client latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kafka_server_zookeeperclientmetrics_zookeeperrequestlatencyms{job=\"kafka\"}"
    }
   ]
  },
  {
   "title": "zookeeper_cluster_down",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg (up{job=\"zookeeper\"}) BY (job)"
    }
   ]
  },
  {
   "title": "zookeeper_status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(up{job=\"zookeeper\"}[5m])"
    }
   ]
  },
  {
   "title": "zookeeper_disconnected_from_ensemble",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "absent(kafka_server_sessionexpirelistener_zookeeperdisconnects_total)"
    }
   ]
  },
  {
   "title": "zookeeper_session_expire_status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "absent(kafka_server_sessionexpirelistener_zookeeperexpires_total)"
    }
   ]
  }
 ]
}